{% set name = "xsar" %}
{% set version = "2024.11.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xsar-{{ version }}.tar.gz
  sha256: 5b511cdee0e8334f307bf6dcb00574801d5a41a82a4d5a2088f563de277dff3a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools_scm
    - setuptools_scm_git_archive
    - pip
  run:
    - python >={{ python_min }}
    - GDAL
    - dask
    - distributed
    - xarray
    - affine
    - rasterio
    - cartopy
    - fiona
    - pyproj
    - xarray-datatree >=0.0.9
    - numpy
    - scipy
    - shapely
    - geopandas
    - fsspec
    - aiohttp
    - pytz
    - psutil
    - jinja2
    - rioxarray
    - lxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - xsar

about:
  description: xsar is a level-1 SAR file reader designed to perform efficient distributed processing algorithm with xarray and dask.
  dev_url: https://github.com/umr-lops/xsar
  doc_url: https://cyclobs.ifremer.fr/static/sarwing_datarmor/xsar/index.html
  home: https://github.com/umr-lops/xsar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xsar is a distributed level 1 SAR file reader
extra:
  recipe-maintainers:
    - oarcher
    - agrouaze
    - Skealz
    - vincelhx
