{% set name = "xsar" %}
{% set version = "2023.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsar-{{ version }}.tar.gz
  sha256: c8effea4d9d054b79fbae3d81e065f6d552dcbb36b31b922d8f0b2a675a8d545

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools_scm
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.8
    - GDAL
    - dask
    - distributed
    - xarray
    - affine
    - rasterio
    - cartopy
    - fiona
    - pyproj
    - xarray-datatree >=0.0.9
    - numpy
    - scipy
    - shapely
    - geopandas
    - fsspec
    - aiohttp
    - pytz
    - psutil
    - jinja2
    - rioxarray

test:
  imports:
    - xsar

about:
  description: xsar is a level-1 SAR file reader designed to perform efficient distributed processing algorithm with xarray and dask.
  dev_url: https://github.com/umr-lops/xsar
  doc_url: https://cyclobs.ifremer.fr/static/sarwing_datarmor/xsar/index.html
  home: https://github.com/umr-lops/xsar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xsar is a distributed level 1 SAR file reader
extra:
  recipe-maintainers:
    - oarcher
    - alevieux
    - agrouaze
