{% set name = "xsar" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/umr-lops/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 64fdde991943420b48e923b5cf08349689627df45bc9c8d1a2280b33868c38fc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools_scm
    - setuptools_scm_git_archive
    - pip
  run:
    - aiohttp
    - cartopy >=0.19.0
    - dask >=2021.6.2
    - gdal >=3.3
    - geopandas
    - importlib_resources
    - jmespath
    - lxml
    - more-itertools
    - rasterio >=1.2.6,<=1.3.0.post1
    - setuptools_scm
    - setuptools_scm_git_archive
    - xarray
    - rioxarray >=0.10
    - pandoc
    - xarray-datatree
    - python >=3.8

test:
  imports:
    - xsar

about:
  description: xsar is a level-1 SAR file reader designed to perform efficient distributed processing algorithm with xarray and dask.
  dev_url: https://github.com/umr-lops/xsar
  doc_url: https://cyclobs.ifremer.fr/static/sarwing_datarmor/xsar/index.html
  home: https://github.com/umr-lops/xsar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xsar is a distributed level 1 SAR file reader
extra:
  recipe-maintainers:
    - oarcher
    - alevieux
    - agrouaze
