{% set name = "xsar" %}
{% set version = "2024.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsar-{{ version }}.tar.gz
  sha256: 786ab84d401223afb4d9eeed6dd06ed8279229793260c15c69222c0541b972d6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools_scm
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.8
    - GDAL
    - dask
    - distributed
    - xarray
    - affine
    - rasterio
    - cartopy
    - fiona
    - pyproj
    - xarray-datatree >=0.0.9
    - numpy
    - scipy
    - shapely
    - geopandas
    - fsspec
    - aiohttp
    - pytz
    - psutil
    - jinja2
    - rioxarray
    - lxml

test:
  imports:
    - xsar

about:
  description: xsar is a level-1 SAR file reader designed to perform efficient distributed processing algorithm with xarray and dask.
  dev_url: https://github.com/umr-lops/xsar
  doc_url: https://cyclobs.ifremer.fr/static/sarwing_datarmor/xsar/index.html
  home: https://github.com/umr-lops/xsar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xsar is a distributed level 1 SAR file reader
extra:
  recipe-maintainers:
    - oarcher
    - alevieux
    - agrouaze
