{% set name = "xsar" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/umr-lops/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a0dd366eb061aab2cf6935cdec82e8af7666aa2a773d1636183a173f8a8ed1ca

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools_scm
    - setuptools_scm_git_archive
    - pip
  run:
    - aiohttp
    - attrs
    - cartopy >=0.19.0
    - dask >=2021.6.2
    - gdal >=3.2.1
    - geopandas
    - importlib_resources
    - jmespath
    - lxml
    - more-itertools
    - pyproj
    - rasterio >=1.2.6
    - setuptools_scm
    - setuptools_scm_git_archive
    - xarray
    - rioxarray
    - shapely
    - python >=3.7,<3.10

test:
  imports:
    - xsar

about:
  description: xsar is a distributed level 1 SAR file reader designed to write efficient distributed processing algorhitm with xarray and dask.
  dev_url: https://github.com/umr-lops/xsar
  doc_url: https://cyclobs.ifremer.fr/static/sarwing_datarmor/xsar/index.html
  home: https://github.com/umr-lops/xsar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xsar is a distributed level 1 SAR file reader
extra:
  recipe-maintainers:
    - oarcher
    - alevieux
